"""Prompts for graph summarization and analysis."""

from .summarizer_prompts import (
    OVERVIEW_PROMPT,
    CLUSTER_ANALYSIS_PROMPT,
    PATTERN_DETECTION_PROMPT,
    ENHANCED_PATTERN_DETECTION_PROMPT,
    RECOMMENDATION_PROMPT,
)

__all__ = [
    "OVERVIEW_PROMPT",
    "CLUSTER_ANALYSIS_PROMPT",
    "PATTERN_DETECTION_PROMPT",
    "ENHANCED_PATTERN_DETECTION_PROMPT",
    "RECOMMENDATION_PROMPT",
]
